#!/usr/bin/env python3
"""Generate an underside-engraved/debossed STL using OpenSCAD.

This script does not directly boolean the mesh in Python. It generates a small
OpenSCAD wrapper around the input STL and subtracts a text volume from the bottom
face. If OpenSCAD is installed, it can also render the marked STL.

Why deboss/engrave rather than raised emboss on the bottom:
- Raised text on the build-plate side creates first-layer/contact problems.
- Recessed text subtracts material from the underside while preserving the broad
  flat bottom around the mark.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

# allow running from repo root without package install
sys.path.insert(0, str(Path(__file__).resolve().parent))
from stl_bounds import bounds  # noqa: E402


def scad_string(input_stl: Path, mark: str, *, size: float, depth: float, font: str,
                rotate_deg: float, x: float | None, y: float | None,
                margin_z: float = 0.02) -> str:
    b = bounds(input_stl)
    minx, miny, minz = b['min']
    maxx, maxy, maxz = b['max']
    cx, cy, _ = b['center']
    tx = cx if x is None else x
    ty = cy if y is None else y
    # Subtract from slightly below bottom up into the model.
    z = minz - margin_z
    cut_depth = depth + margin_z

    # Use absolute path; escape backslashes/quotes for OpenSCAD string.
    stl = str(input_stl.resolve()).replace('\\', '/').replace('"', '\\"')
    mark_escaped = mark.replace('"', '\\"')
    font_escaped = font.replace('"', '\\"')

    return f'''// Generated by scripts/mark-stl-bottom.py
// Input bounds min=[{minx:.4f},{miny:.4f},{minz:.4f}] max=[{maxx:.4f},{maxy:.4f},{maxz:.4f}]
// Mark: {mark_escaped}

$fn = 24;

difference() {{
  import("{stl}", convexity=10);

  // Recessed underside serial mark.
  // The text volume starts just below the bottom face and cuts upward.
  translate([{tx:.4f}, {ty:.4f}, {z:.4f}])
    rotate([0, 0, {rotate_deg:.4f}])
      linear_extrude(height={cut_depth:.4f})
        mirror([1, 0, 0])
          text("{mark_escaped}",
             size={size:.4f},
             font="{font_escaped}",
             halign="center",
             valign="center");
}}
'''


def main() -> int:
    ap = argparse.ArgumentParser(description='Engrave/deboss a serial mark into the bottom of an STL via OpenSCAD.')
    ap.add_argument('--input', required=True, type=Path)
    ap.add_argument('--mark', required=True, help='Short physical mark, e.g. D3B001')
    ap.add_argument('--output', required=True, type=Path, help='Output marked STL path')
    ap.add_argument('--scad-output', type=Path, default=None, help='Optional generated SCAD path')
    ap.add_argument('--size', type=float, default=3.2, help='Text size in mm')
    ap.add_argument('--depth', type=float, default=0.4, help='Engraving depth in mm')
    ap.add_argument('--font', default='Liberation Sans:style=Bold')
    ap.add_argument('--rotate-deg', type=float, default=90.0)
    ap.add_argument('--x', type=float, default=None)
    ap.add_argument('--y', type=float, default=None)
    ap.add_argument('--no-render', action='store_true', help='Only generate SCAD; do not call OpenSCAD')
    ap.add_argument('--openscad', default='openscad', help='OpenSCAD binary path')
    args = ap.parse_args()

    args.input = args.input.resolve()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    scad_path = args.scad_output or args.output.with_suffix('.scad')
    scad_path.parent.mkdir(parents=True, exist_ok=True)

    scad_path.write_text(scad_string(
        args.input, args.mark,
        size=args.size,
        depth=args.depth,
        font=args.font,
        rotate_deg=args.rotate_deg,
        x=args.x,
        y=args.y,
    ))

    meta = {
        'input': str(args.input),
        'output': str(args.output),
        'scad': str(scad_path),
        'mark': args.mark,
        'size_mm': args.size,
        'depth_mm': args.depth,
        'font': args.font,
        'rotate_deg': args.rotate_deg,
        'bounds': bounds(args.input),
    }
    print(json.dumps(meta, indent=2))

    if args.no_render:
        return 0

    openscad = shutil.which(args.openscad) or args.openscad
    try:
        subprocess.run([openscad, '-o', str(args.output), str(scad_path)], check=True)
    except FileNotFoundError:
        print('ERROR: OpenSCAD not found. Install it or rerun with --no-render.', file=sys.stderr)
        return 127
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
